### ISSUE TITLE
when upload the discussion i got missing data

### ISSUE THREAD

**Issue by adilaminuddin** [AndreasElia/laravel-firefly#83] opened 2023-03-28 16:02 UTC
Insert data like this :
** Test Data with Bold and Heading 1**
In database and  output : 
trong>Test with Bold and Heading 1</strong><p><br></p><p>Test data </

**Comment by andreaselia** [comment] 2023-07-08 08:13
Hi @adilaminuddin, I don't believe I've seen this issue before. Did you manage to resolve your issue?

I'm going to close this due to the age of the issue and nobody else reporting any issues with it, but feel free to let me know that the issue persists and some steps to reproduce it and I'll take a look.

Thanks!

**Closed as completed by andreaselia** 2023-07-08 08:13 UTC
